### ISSUE TITLE
Catch exceptions thrown by GoogleScraper

### ISSUE THREAD

**Issue by mrose17** [starsnotinjars/Automatic-Website-Categorizers#3]
%  GoogleScraper -m http -s bing --keyword-file keyword10.txt > output.txt
    ...
    Encoding error : input conversion failed due to input error, bytes 0x21 0x00 0x00 0x00
    2017-02-07 20:02:35,864 - GoogleScraper.parsing - ERROR - switching encoding: encoder error, line 1, column 1 (<string>, line 1)
    Exception in thread [bing]HttpScrape:
    Traceback (most recent call last):
      File "/Users/mrose/homebrew/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/http_mode.py", line 306, in run
        if not self.search(rand=True):
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/http_mode.py", line 294, in search
        super().after_search()
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/scraping.py", line 360, in after_search
        if not self.store():
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/scraping.py", line 280, in store
        self.parser.parse(self.html)
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/parsing.py", line 120, in parse
        self._parse()
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/parsing.py", line 153, in _parse
        self.num_results_for_query = self.first_match(num_results_selector, self.dom)
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/parsing.py", line 272, in first_match
        match = self.advanced_css(selector, element=element)
      File "/Users/mrose/homebrew/lib/python3.6/site-packages/GoogleScraper/parsing.py", line 251, in advanced_css
        value = element.xpath(self.css_to_xpath(selector))[0].text_content()
    AttributeError: 'NoneType' object has no attribute 'xpath'
    
perhaps contact the author and get their advice?

**Comment by mrose17** [comment]
OBE.
